@echo off
echo Setting environment variables in Vercel...

echo Setting DATABASE_URL...
echo mongodb+srv://chiru:chiru@cluster0.yylyjss.mongodb.net/ev_bunker?retryWrites=true^&w=majority^&appName=Cluster0 | vercel env add DATABASE_URL production

echo Setting NEXTAUTH_SECRET...
echo SuqrDIOYjveY0px3uNru4X0qc1No1DfG | vercel env add NEXTAUTH_SECRET production

echo Setting NEXTAUTH_URL...
echo https://ev-bunker-chiranjeevi005s-projects.vercel.app | vercel env add NEXTAUTH_URL production

echo Setting REDIS_URL...
echo rediss://default:AR-MAAImcDIyM2MyNzA5NmRjMzg0Nzg1OTY3N2FiOTQ0MGY1NzEzMXAyODA3Ng@enabled-antelope-8076.upstash.io:6379 | vercel env add REDIS_URL production

echo Setting RAZORPAY_KEY_ID...
echo rzp_test_RPS4VC3EINUb3D | vercel env add RAZORPAY_KEY_ID production

echo Setting RAZORPAY_KEY_SECRET...
echo 87TSpJ63uYMG4ZPpppQWFNQm | vercel env add RAZORPAY_KEY_SECRET production

echo Setting NEXT_PUBLIC_RAZORPAY_KEY_ID...
echo rzp_test_RPS4VC3EINUb3D | vercel env add NEXT_PUBLIC_RAZORPAY_KEY_ID production

echo Setting ARCJET_KEY...
echo ajkey_01k68gmjgwemkazwfw6vndwnw9 | vercel env add ARCJET_KEY production

echo Setting NODE_ENV...
echo production | vercel env add NODE_ENV production

echo All environment variables set successfully!